#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'yum'
cookbook 'sudo'
cookbook 'chef-solo-search', git: 'https://github.com/edelight/chef-solo-search.git'

cookbook 'freeswitch', git: 'https://github.com/mojolingo/freeswitch-cookbook.git'
cookbook 'mysql'
cookbook 'redisio'
cookbook 'ejabberd', git: 'git@github.com:mojolingo/ejabberd.git'
